language: nodez_js
node_js: 
  - "v11.0.0"
services: 
  - postgresql
  - redis-server
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
script:
  - npm ci
  - npm test
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coverage