language: nodez_js
node_js: 
  - "v11.0.0"
services: 
  - postgresql
  - redis-server
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm ci
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coverage