version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: cache
    expose:
      - 6379
  web:
    build: .
    ports:
      - "3000:3000"
    links:
        - redis
    environment:
     - ECOMMERCE_NODE_ENV=development
     - REDIS_URL=redis://cache
  