# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ admincontroller ]
  pull_request:
    branches: [ admincontroller ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: node client.js
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0

    env:
      ECOMMERCE_NODE_ENV: test
      REDIS_HOST: redis
          # The default Redis port
      REDIS_PORT: 6379
      ECOMMERCE_DATABASE_TEST_URL: postgres://localhost/postgres