# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ admincontroller ]
  pull_request:
    branches: [ admincontroller ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ECOMMERCE_DATABASE_TEST
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ECOMMERCE_DATABASE_TEST
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    env:
      ECOMMERCE_NODE_ENV: test
      ECOMMERCE_DATABASE_TEST_URL: 'postgres://postgres:postgres@localhost:5432/ECOMMERCE_DATABASE_TEST'
      FACEBOOK_APP_ID: ${{secrets.FACEBOOK_APP_ID}}
      FACEBOOK_CALLBACK_URL: ${{secrets.FACEBOOK_CALLBACK_URL}}
      FACEBOOK_APP_SECRET: ${{secrets.FACEBOOK_APP_SECRET}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      API_KEY: ${{secrets.API_KEY}}
      DOMAIN: ${{secrets.DOMAIN}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      SALT: ${{secrets.SALT}}
      NODE_MAILER_EMAIL: ${{secrets.NODE_MAILER_EMAIL}}
      NODE_MAILER_PASSWORD: ${{secrets.NODE_MAILER_PASSWORD}}
      REDIS_URL: 'redis://127.0.0.1:6379'
      ADMIN_TOKEN: {{secrets.ADMIN_TOKEN}}